services:
  postgres:
    image: postgres:16-alpine
    container_name: smartrecruit-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: smartrecruit-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  minio:
    image: minio/minio
    container_name: smartrecruit-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: smartrecruit-keycloak
    ports:
      - "8081:8080" # Exposed on 8081 so it doesn't conflict with Spring Boot on 8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev --import-realm
    volumes:
      # This line mounts your local directory into Keycloak's internal directory
      - ./infrastructure/keycloak/themes/smartrecruit:/opt/keycloak/themes/smartrecruit
      # Mount the folder where you will place your realm-export.json
      - ./infrastructure/keycloak/import:/opt/keycloak/data/import

  mailpit:
    image: axllent/mailpit
    container_name: smartrecruit-mailpit
    ports:
      - "8025:8025" # Web UI to visually inspect caught emails
      - "1025:1025" # Fake SMTP Port for Spring Boot to send emails to
    environment:
      MP_MAX_MESSAGES: 500

  adminer:
    image: adminer
    container_name: smartrecruit-adminer
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres-data:
  minio-data:
